CREATE TABLE PRODUCTOS (
  ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  NOMBRE VARCHAR(50) NOT NULL UNIQUE,
  COSTO NUMBER(9, 2),
  PRECIO_1 NUMBER(9, 2) NOT NULL,
  PRECIO_2 NUMBER(9, 2),
  PRECIO_3 NUMBER(9, 2),
  RUBRO VARCHAR(50),
  PROVEEDOR_ID NUMBER(3,0),
  CREADO DATE DEFAULT CURRENT_DATE, 
  MODIFICADO DATE
  );

CREATE TABLE CLIENTES (
  ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  NOMBRE VARCHAR(50) NOT NULL UNIQUE,
  DIRECCION VARCHAR(50),
  DIRECCION_2 VARCHAR(50),
  TELEFONO VARCHAR(20),
  EMAIL VARCHAR(50),
  CUIT VARCHAR(11) UNIQUE,
  IVA VARCHAR(30) NOT NULL,
  );

CREATE TABLE VENTA (
  ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  FECHA DATE NOT NULL,
  HORA TIME NOT NULL,
  PRODUCTO_ID INT,
  CLIENTE_ID INT,
  MONTO NUMBER(9,2) NOT NULL,
  
  TIPO_COMPROBANTE VARCHAR(10), 
  NRO_COMPROBANTE VARCHAR(20),
  CAE VARCHAR(14),
  VENCIMIENTO_CAE DATE
);

CREATE TABLE VENTAS_DETALLE (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    VENTA_ID INT NOT NULL,
    PRODUCTO_ID INT NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO NUMBER(9, 2) NOT NULL,
    SUBTOTAL NUMBER(9, 2) NOT NULL
);
