CREATE TABLE PRODUCT {
  ID NUMBER(5,0) PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  NOMBRE VARCHAR2(50) NOT NULL UNIQUE,
  COSTO NUMBER(9, 2),
  PRECIO_1 NUMBER(9, 2) NOT NULL,
  PRECIO_2 NUMBER(9, 2),
  PRECIO_3 NUMBER(9, 2),
  RUBRO VARCHAR(50),
  PROVEEDOR_ID NUMBER(3,0)
  };

